### ISSUE TITLE
ETP-729: Errors in Etendo Gradle Plugin Version 1.4.0 (and 1.5.0)

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/com.etendoerp.gradleplugin#42]
# Error's description
This bug report describes two errors encountered when using the Etendo Gradle Plugin version 1.4.0 in the Etendo Classic environment.

 # Steps to reproduce the error
When running the prepareConfig task in Etendo Classic with all bundles included, the following error appears:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'etendo'.
> Failed to notify project evaluation listener.
   > ././build/lib/runtime/snappy-java-1.1.8.1.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
```

Error 2: antSetup Task Execution Failure
When attempting to set up an Etendo Classic environment in JAR, the antSetup task fails with the following error:

```
> Task :antSetup FAILED
Caching disabled for task ':antSetup' because:
  Build cache is disabled
Task ':antSetup' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
[ant:echo] Launching configuration application...
:antSetup (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.179 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':antSetup'.
> taskdef class org.openbravo.configuration.ConfigurationApp cannot be found
   using the classloader AntClassLoader[..]

```
 # Solution Design (optional)
Investigate and resolve the issue with the snappy-java dependency causing the failure in the prepareConfig task.
Verify and correct the configuration for the antSetup task to ensure the ConfigurationApp class is properly located and loaded by the AntClassLoader during setup.

# Use/Test Cases

Given
- Etendo Classic environment with the Etendo Gradle Plugin version 1.4.0.

When
- prepareConfig is executed with all bundles.
- antSetup is run in an Etendo Classic environment in JAR mode.

Then
- ./gradlew prepareConfig should execute successfully without dependency-related errors.
- ./gradlew setup should complete successfully, loading the ConfigurationApp class as expected.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.5.1](https://github.com/etendosoftware/com.etendoerp.gradleplugin/releases/tag/1.5.1) ⚡ 🚀
